title: Juan Camilo Olaya Monsalve
logo: https://github.com/JuanCamiloOlaya/JuanCamiloOlaya.github.io/blob/main/_assets/ai_photo.jpg
description: Economist and Data Nerd
show_downloads: false
theme: jekyll-theme-minimal
