title: Juan Camilo Olaya Monsalve
description: >
  Economist and Data Nerd

  Economist well versed in mathematical modelling and data science dedicated to leveraging data-driven insights to drive real-world business problems using solid analytical skills.
logo: /assets/images/ai_photo.jpg
show_downloads: false
theme: jekyll-theme-minimal
github: false
